apiVersion: v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: my-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-container
  template:
    metadata:
      labels:
        app: my-container
    spec:
      containers:
      - name: my-container
        image: 383265273024.dkr.ecr.us-east-1.amazonaws.com/my-new-image:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: my-container
spec:
  selector:
    app: my-container
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
